### ISSUE TITLE
Gerador de grafo aleatório

### ISSUE THREAD

**Issue by Ercampa2** [MarciovsRocha/grafos#4]
Gerador de grafo aleatório que segue o modelo “livre de escala” visto em 
aula, em que vértices de maior grau possuem maior probabilidade de serem 
conectados. O grafo deve ser ponderado, com pesos (valores inteiros) entre 1 e 100, 
também  definidos  de  maneira  aleatória.  Os  vértices  devem  ser  rotulados  de  acordo 
com os nomes de usuários apresentados no arquivo “Users.txt”, fornecido junto com 
este  documento.  A  função  deste  gerador  deve  ter  os  seguintes  parâmetros  de 
entrada: 
o Número de vértices; 
o Número de arestas; 
o Se o grafo é direcionado ou não-direcionado.

**Comment by MarciovsRocha** [comment]
created
